services:
  mongodb:
    image: mongo:latest
    container_name: homelab-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build: ./backend
    container_name: homelab-backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongodb:27017/homelab
    depends_on:
      - mongodb

volumes:
  mongodb_data: